name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run on each push to the main branch
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: 0xAnthonyRx
          
          # === VISUALS ===
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Lagos
          
          # === LANGUAGES (Fixing the Jupyter Issue) ===
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, Jupyter Notebook, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_details: lines, percentage
          
          # === 3D CALENDAR (The Aesthetic Part) ===
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
